import os

PATH_ = os.getcwd()
PATH_SAVES = os.path.join(PATH_, 'save_files')
PATH_CUSTOMER = os.path.join(PATH_SAVES, '{}')
PATH_CUSTOMER_SAVE = os.path.join(PATH_SAVES, '{}', '{}')
PATH_CUSTOMER_SAVE_DETAILS = os.path.join(PATH_SAVES, '{}', '{}', 'prescan_info', 'details.json')
PATH_CUSTOMER_SAVE_HARDWARE = os.path.join(PATH_SAVES, '{}', '{}', 'hardware-list.json')
PATH_CUSTOMER_SAVE_SERVICE = os.path.join(PATH_SAVES, '{}', '{}', 'service.json')
PATH_CUSTOMER_TIMESTAMP_NAME = os.path.join(PATH_SAVES, '{}', 'timestamp-name.json')
PATH_CUSTOMER_LOGS = os.path.join(PATH_SAVES, '{}', '{}', 'logs')
PATH_CUSTOMER_RAWS = os.path.join(PATH_SAVES, '{}', '{}', 'raws')
PATH_CUSTOMER_PRESCAN = os.path.join(PATH_SAVES, '{}', '{}', 'prescan_info')
PATH_CUSTOMER_PRIMARY = os.path.join(PATH_SAVES, '{}', '{}', 'primary_scan_info')
PATH_CURRENT_PREVIEW = os.path.join(PATH_, 'app', 'static', 'javascript', 'current_preview')
PATH_DOWNLOAD_DUMP = os.path.join(PATH_, 'app', 'generate_import_csv', 'download_dump', '{}')
